# The URL of your website.
# End your URL with a `/` trailing slash, e.g. `https://example.com/`.
baseurl = "https://our-hugo-test.netlify.com/"
languageCode = "fr"
defaultContentLanguage = "fr"
theme = "my-hugo-bootstrap"
enableGitInfo = true

# Title of your site
title = "Tester HUGO"

# Pagination
paginate = 4
paginatePath = "page"

[taxonomies]
  tag = "tags"
  category = "categories"

# Google analytics
# googleAnalytics = "UA-47268287-3"


[languages.fr]
  languageName = "Français"

  copyright = "© copyright 2018 RERO"
  
  [[languages.fr.menu.main]]
    url = "/"
    name = "Accueil"
    weight = 1
  [[languages.fr.menu.main]]
    url = "/a-propos/"
    name = "À propos"
    weight = 2
  [[languages.fr.menu.main]]
    url = "/categories/ils/"
    name = "ils"
    weight = 3
  [[languages.fr.menu.main]]
    url = "/categories/test/"
    name = "test"
    weight = 4
  [[languages.fr.menu.main]]
    url = "/contact/"
    name = "Contact"
    weight = 5

[languages.en]
  languageName = "English"

  # Replace the default footer message with a localized message
  copyright = "© copyright 2018 RERO"
  
  [[languages.en.menu.main]]
    url = "/en/"
    name = "Home"
    weight = 1
  [[languages.en.menu.main]]
    url = "/about/"
    name = "About"
    weight = 2
  [[languages.en.menu.main]]
    url = "/contact/"
    name = "Contact"
    weight = 3

[languages.de]
  languageName = "Deutsch"

  copyright = "© copyright 2018 RERO"

  [[languages.de.menu.main]]
    url = "/de/"
    name = "Start"
    weight = 1
  [[languages.de.menu.main]]
    url = "/about/"
    name = "Über uns"
    weight = 2
  [[languages.de.menu.main]]
    url = "/contact/"
    name = "Kontakt"
    weight = 3

# Links format

[permalinks]
  post = "/:filename/"

[params]
  # Main sections (currently used for the recent posts in the sidebar)
  mainSections = ["post"]

  # Default author
  # author = "John Doe"

  # Date format (default: Jan 2, 2006)
  date_format = "2006-01-02"

  # Display post summaries instead of content in list templates (default: true)
  # truncate = false

  # Display social sharing buttons (default: true)
  # share = true 

  [params.sidebar]
    # Whether to show the recent posts or not (default: true)
    # showRecent = false

    # Whether to show the taxonomies or not (default: true)
    # showTaxonomy = false

    # How many posts to show on the sidebar (Default: 5)
    # num_recent_posts = 5
